# Monitor config file change/delete and reload/release config file.
fileWatchService: true

# Plugin function settings.
settings:
  # Detect period(tick(s)(1 tick = 20 seconds))
  detectPeriod: 5
  # Teleport when too far from target or in different world.
  teleport:
    # Enable?
    enable: true
    # Teleport trigger distance(distance > this)(block).
    distance: 64
    # Delay between teleport and switch target(tick(s)(1 tick = 20 seconds)).
    switchDelay: 100
